# Generated by Django 2.2.8 on 2020-09-20 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='create_by',
        ),
    ]
